repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
    name: fix end of files
    description: Ensures that a file is either empty, or ends with one newline.
    entry: end-of-file-fixer
    types: [text]
    language: python
  - id: check-docstring-first
    name: check-docstring-first
    description: Checks for a common error of placing code before the docstring.
    entry: check-docstring-first
    types: [python]
    language: python
  - id: check-ast
    name: check-ast
    description: Simply check whether files parse as valid python.
    entry: check-ast
    types: [python]
    language: python
  - id: check-case-conflict
    name: check-case-conflict
    entry: check-case-conflict
    types: [python]
    language: python
  - id: check-yaml
    name: check-yaml
    entry: check-yaml --allow-multiple-documents
    types: [file, yaml]
    language: python
  - id: check-added-large-files
    name: check-added-large-files
    entry: check-added-large-files --maxkb=1024
    types: [file]
    language: python
# Using this mirror lets us use mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.8.0
  hooks:
  - id: black
    name: black
    entry: poetry run black
    types: [python]
    language: python
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.7
  hooks:
  - id: ruff
    name: ruff
    entry: poetry run ruff check . --fix
    types: [python]
    language: python
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run mypy --no-strict-optional --ignore-missing-imports --install-types --non-interactive
    types: [python]
    language: python
